mdapi-source/original-package/objects/Travel_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Travel Expense</label>
    <nameField>
        <label>Travel Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/sfdx_isv_pkg004/main/default/apex/TravelExpenseDomainTest.cls
@isTest (SeeAllData=false)
private class TravelExpenseDomainTest {
    static testMethod void validateGetAll() {
        List<Travel_Expense__c> travelExpenses = new List<Travel_Expense__c>();

        travelExpenses.add(new Travel_Expense__c(
            name        = 'Sample Travel Expense',
            amount__c   = 2325.29,
            approved__c = false
        ));

        INSERT travelExpenses;
        System.debug('-->travelExpenses after INSERT: ' + travelExpenses);

        TravelExpenseDomain txd = new TravelExpenseDomain();

        List<Travel_Expense__c> retrievedTravelExpenses = txd.getAll();

       // Test that the trigger correctly updated the price
       System.assertEquals(1, retrievedTravelExpenses.size());
    }
}